### ISSUE TITLE
Git unhandled error should clean up 

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#164] opened 2024-11-08 09:20 UTC
If there is an issue in Git, then the whole cruiz process tree remains running, and you have to manually kill it.

This should be more elegant.

**Comment by markfinal** [comment] 2024-11-15 21:55
This is a duplicate of https://github.com/markfinal/cruiz/issues/163 as there is no other fix than to catch the exception

**Closed by markfinal** 2024-11-15 21:55 UTC
