### ISSUE TITLE
Conan types leaking into the UI

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#158] opened 2024-08-14 13:46 UTC
Two separate reports of this today, e.g.

```
CRITICAL:cruiz.commands.messagereplyprocessor:Conan has leaked into message queue object dump:
CRITICAL:cruiz.dumpobjecttypes:<class 'cruiz.workers.utils.message.Success'>
CRITICAL:cruiz.dumpobjecttypes: _data: <class 'list'>
CRITICAL:cruiz.dumpobjecttypes:  0: <class 'dict'>
CRITICAL:cruiz.dumpobjecttypes:   id: <class 'str'>
CRITICAL:cruiz.dumpobjecttypes:   options: <class 'dict'>
CRITICAL:cruiz.dumpobjecttypes:    generate_docs: <class 'conans.model.options.PackageOptionValue'>
```

**Comment by markfinal** [comment] 2024-08-15 19:57
This is a duplicate of https://github.com/markfinal/cruiz/issues/49 which is already fixed in main, but is not yet in any release.

**Closed by markfinal** 2024-08-15 19:57 UTC
Labels: duplicate
